app/actions/idea.go, app/handlers/idea.go, app/handlers/idea_test.go, app/models/feedback.go, main.go, public/assets/styles/main.scss, public/components/ResponseForm.tsx, public/components/common/DisplayError.tsx, public/pages/site/ShowIdeaPage.scss, public/pages/site/ShowIdeaPage.tsx, public/services/IdeaService.ts, routes.go
=> Allow members to update idea's title and description

app/pkg/web/context.go
It fixes #253 by adding a check for the standard `X-Forwarded-Proto` header.
=> Fix BaseURL when hosted behind a TLS reverse proxy

app/pkg/dbx/dbx.go, app/storage/postgres/idea.go, app/storage/postgres/notifications.go, app/storage/postgres/tag.go, app/storage/postgres/tenant.go, app/storage/postgres/user.go
**Issue:** closes #277
- `trx.Execute` now returns number of affected rows.
- Add/Remove support rely on number of affected rows instead of additional SELECT query.
=> refactor: add/remove supporters

app/handlers/common.go, app/handlers/signin_test.go, app/pkg/web/context.go, app/pkg/web/renderer.go, views/410.html
**Issue:**  closes #170
Introduces the `410 GONE` page used for verification keys that have been user or expired
=> render 410 page when link has been used/expired

app/handlers/avatar.go
**Issue:**  closes #338
Detect Gravatar content type instead of forcing it to `image/png`, IE doesn't like it.
=> fix for gravatar issue on IE11

.circleci/config.yml
**Issue:**  #337
Updates to latest builder image, which uses Go 1.10.1 (this was missing from #342)
=> update to latest circle ci builder (go 1.10.1)

app/handlers/invite.go, app/pkg/email/email.go, app/pkg/email/mailgun/mailgun.go, app/pkg/email/smtp/smtp.go, app/tasks/tasks.go
**Issue:**  closes #336
Add two tags to maligun deliveries:
```
Add `o:tag="tenant:<subdomain>"` (when running on Multi-tenant mode)
Add `o:tag="event:<event_name>"`
```
=> add tags to mailgun deliveries

app/middlewares/domain.go, app/middlewares/domain_test.go, app/storage/inmemory/tenant.go
**Issue:**  related to #274
This will only add Canonical Link if the request is not already on the correct domain
=> fix: only add canonical link if needed

.test.env, app/handlers/oauth.go, app/handlers/oauth_test.go, app/handlers/signin_test.go, app/middlewares/setup.go, app/pkg/env/env.go, app/pkg/env/env_test.go, app/pkg/mock/oauth.go, app/pkg/oauth/oauth.go, app/pkg/web/context.go, app/pkg/web/oauth.go, app/pkg/web/oauth_test.go, app/pkg/web/util/webutil.go, app/pkg/web/util/webutil_test.go
=> enhancement: correct use of OAuth state

app/handlers/images.go, app/handlers/images_test.go
=> fix: use lowercase email for gravatar

app/handlers/apiv1/tag.go, app/models/feedback.go, app/models/identity.go, app/pkg/assert/assert.go, app/pkg/dbx/mapping.go, app/pkg/email/email.go, app/pkg/markdown/renderer.go, app/pkg/web/binder_test.go, app/pkg/web/context.go, app/pkg/web/engine.go, app/storage/postgres/post.go, app/storage/postgres/user.go, public/components/common/Legal.tsx, public/pages/Administration/pages/AdvancedSettings.page.tsx, public/pages/MySettings/components/APIKeyForm.tsx, public/pages/ShowPost/components/ShowComment.tsx, tests/lib/components.ts
There are a lot of typos in comments. Also, variable names and functions named not correct. This MR fixed these problems.
=> Fix typos in comments, variables and function names

public/assets/styles/grid.scss, public/pages/Administration/components/SideMenu.scss
**Issue:**  #580 
Correctly position the burger menu collapser at the top right corner of the container that it is in.
=> [fider/580] Burger menu is incorrectly positioned

app/cmd/routes.go, app/handlers/apiv1/post.go, app/handlers/apiv1/post_test.go, app/handlers/post.go
**Issue:**  #581 
- Adjust the handlers to send back a 404 if the `ParamAsInt("number")` validation fails.
- Add an endpoint to retrieve a post (Rest)
=> [fider/581] Invalid posts should return a 404 and not a 500

public/services/utils.spec.ts
**Issue:** Unit test was using UTC comparing to local time. Therefore, the test failed in time zone UTC +1.
I edited the test values of the failing unit test to use local time instead of UTC.
=> Unit tests: UTC changed to local time

app/cmd/routes.go, app/handlers/common.go, package-lock.json, public/assets/styles/main.scss, public/index.tsx, public/services/navigator.spec.ts, public/services/navigator.ts, views/403.html, views/404.html, views/410.html, views/500.html, views/base.html, views/browser-not-supported.html, views/index.html, views/legal.html, views/not-invited.html, views/pending-activation.html
We redirect users to /browser-not-support on two occasions:
- IE <=10
- Any browser that support only CSP 1 (and not CSP 2), like Chrome ~30 or older. These browsers fails to run inline script with nonce, thus failing Fider.initialize as well.
=> enhancement: create page for browser not supported

app/pkg/web/renderer.go, public/index.tsx, public/services/fider.ts, public/tsd.d.ts, views/403.html, views/404.html, views/410.html, views/500.html, views/base.html, views/browser-not-supported.html, views/index.html, views/legal.html, views/not-invited.html, views/pending-activation.html
Replace our inline javascript with a JSON payload that is then parsed by our external script.
=> fix: older browsers cannot execute inline javascript with CSP

app/storage/postgres/post.go, app/storage/postgres/subscription_test.go
**Issue:**  fix regression caused by #625
=> fix: notifications were sent even without subscription

app/pkg/web/testdata/basic.html, app/pkg/web/testdata/props.html, app/pkg/web/testdata/tenant.html, app/pkg/web/testdata/user.html, public/index.tsx, public/services/notify.ts, public/services/toastify.tsx, views/index.html, webpack.config.js
=> enhancement: move react-toastify to its own bundle

package-lock.json, package.json, public/AsyncPages.tsx, public/index.tsx, public/pages/Administration/pages/AdvancedSettings.page.tsx, public/pages/Administration/pages/Export.page.tsx, public/pages/Administration/pages/GeneralSettings.page.tsx, public/pages/Administration/pages/Invitations.page.tsx, public/pages/Administration/pages/ManageAuthentication.page.tsx, public/pages/Administration/pages/ManageMembers.page.tsx, public/pages/Administration/pages/ManageTags.page.tsx, public/pages/Administration/pages/PrivacySettings.page.tsx, public/pages/CompleteSignInProfile/CompleteSignInProfile.page.tsx, public/pages/Home/Home.page.tsx, public/pages/MyNotifications/MyNotifications.page.tsx, public/pages/MySettings/MySettings.page.tsx, public/pages/OAuthEcho/OAuthEcho.page.tsx, public/pages/ShowPost/ShowPost.page.tsx, public/pages/SignIn/SignIn.page.tsx, public/pages/SignUp/SignUp.page.tsx, public/pages/UI/UIToolkit.page.tsx, webpack.config.js
=> tooling: replace react-loadable with react lazy

app/cmd/routes.go, app/handlers/apiv1/post.go, app/storage/inmemory/post.go, app/storage/postgres/post.go, app/storage/postgres/post_test.go, app/storage/storage.go
=> feature: add API to return list of voters

.gitignore, Gopkg.toml, Procfile, heroku.yml, package.json
**New feature:**  
This will allow deploying a fider application really easily on Heroku, allowing users to test the application without any line of code, or even to deploy a fully-functioning fider instance for $0.
Steps to deploy on heroku:
- Fork the repository (for auto-deployment from your github account) or clone it locally
- Create an Heroku app : https://dashboard.heroku.com/new-app
- Add a Postgresql add-on on the app (https://elements.heroku.com/addons/heroku-postgresql)
- Add Go buildpack : https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-go
- Add Nodejs buildpack : https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-nodejs
- Setup application's environment variables on Heroku (I'm using mailgun but use SMTP equivalent if needed) : `EMAIL_MAILGUN_API`, …
=> Allow heroku deployment

app/pkg/rand/random.go
**Issue:**  secret tokens, including session cookies and signin tokens sent by email, are generated with `rand.String` method, which uses the `math/rand` pseudrandom number generator. As stated in the Go [documentation](https://golang.org/pkg/math/rand/), this package is not suited to generate sensitive data.
This Pull Request replaces the underlying PRNG (`math/rand`) with `crypto/rand`, a cryptographically secure PRNG.
=> security: replace math/rand with crypto/rand to generate secret strings

app/actions/oauth.go, app/pkg/validate/general.go
**Issue:** #880 
Removed the automatic lowercase on OAuth `AuthorizeURL`, `TokenURL` and `ProfileURL`, as URLs are case-sensitive
=> fix: removed auto-lower on URLs (OAuth)

app/pkg/tpl/funcs.go, public/pages/Administration/components/webhook/WebhookTemplateInfoModal.tsx
**Issue:** #1026
I've implemented `truncate` function that can be used in templates to shorten strings. It accepts *string* as first argument and *max length* as the second one. If given *string* is longer than *max length*, it truncates it and adds ellipsis at the end, so output string will have length that equal to *max length* argument.
This can be used to forward messages to services that have a limit on message length. For example, webhook for Discord will look like this:
```
{
"content": "",
"embeds": [
{
"title": {{ quote .post_title }},
"type": "rich",
"description": "{{ truncate (escape .post_description) 4000 }}",
"url": {{ quote .post_url }},
"author": {
"name": {{ quote .author_name }},
"icon_url": {{ quote .author_avatar }}
}
}
]
}
```
In this example `{{ truncate …
=> Implement "truncate" template function

app/cmd/ping.go
Updated Ping command to fix health check errors
**Issue:** https://github.com/getfider/fider/issues/1047
When Host Domain is set, the Docker health check used to return errors.
This PR fixes that issue and also adds support for health checks if the app is running on ports other than the default 3000.
=> Fix: Healthcheck errors if Host Domain set

public/assets/styles/utility/display.scss, public/pages/ShowPost/components/VotesModal.tsx
**Issue:** All scrollbars would always be visible in the `VotesModal` component. See #1133
=> Scrollbars would always be visible in the `VotesModal` component

migrations/202406111146_add_posts_user_id_index.sql
**Issue:** 
As the number of users and/or posts grows, search performance goes down significantly (query duration >= 30s in our case).
Indexing the user_id column in the posts table fixes the issue.
=> Added migration to create missing posts.user_id index

app/handlers/apiv1/post.go
**Issue:** https://github.com/getfider/fider/issues/1143
**Reasoning behind bug:** In the code for getViewData, by default statuses only contains "open", "started" and "planned", since  https://fider.io/docs/api#list-posts also uses the same function to generate the sql, the returned posts will only have "open", "started" and "planned" statuses. This conflicts with the documentations.
https://github.com/getfider/fider/blob/e55a144ab4aaeed1383bf0d9367cd80bfb7ec4a2/app/services/sqlstore/postgres/common.go#L33-L37
**Proposed changes:**
Since the getViewData function is used across the app, updating statuses here might cause problems on other parts of the app, I decided to create a conditional on the route handler for the API to always set the view Query Params to "all" if it is not …
=> fix: setting default "view" query params to "all"

go.mod, public/components/common/form/Select.tsx
**Issue:** https://github.com/getfider/fider/issues/730
**Description of changes:**
- Refactored form/Select component to funcitonal component
- Kept all the original functionality and jsx code
**Question:**
- When working on this, my terminal threw an error: ```invalid go version '1.22.0': must match format 1.23``` which required me to change the go.mod to 1.22, let me know if I need to change it back and how I can fix this error!
=> refactor: Migrate Select component to functional component using useState hook

go.mod
**Issue:** 
Sorry I was not able to push this change in time before https://github.com/getfider/fider/pull/1176 's merge
**Description of changes:**
- Changed version in go.mod to 1.22.0
**Reasoning:**
- The error on my end ```invalid go version '1.22.0': must match format 1.23``` was caused by my go version being 1.19, I updated to 1.22 and the error is gone, I have changed the version in ```go.mod``` back to 1.22.0.
=> Fix: changing go version in go.mod back to 1.22.0

CONTRIBUTING.md, Makefile
Hello ! 
Update contributing guide to be compliant with [Docker compose V2](https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2) by changing command `docker-compose` to `docker compose`
Update 404 link in the `Makefile` : 
* [404 Link](https://www.thapaliya.com/posts/well-documented-makefiles/) to [New link](https://www.thapaliya.com/en/writings/well-documented-makefiles/)
Just a small PR while reading the contributing guide for the first time, I did not open any issue for this (should I ?)
=> Update contributing doc

app/handlers/apiv1/post.go, app/tasks/delete_post.go, app/tasks/delete_post_test.go
=> Fix: No webhook message when post deleted with no comment.

Dockerfile, go.mod, go.sum
**Issue:** #1145
- Changed the runtime base image from Debian Bullseye to Debian Bookworm for better security and package support.
- Upgraded Node.js version from 18 to 22 in the UI build step for improved performance and compatibility with newer features.
- Updated Go library `github.com/gomarkdown/markdown` to fix [CVE-2023-42821](https://nvd.nist.gov/vuln/detail/CVE-2023-42821).
=> Update Markdown dependency and Dockerfile to Debian Bookworm / Node.js 22

app/middlewares/security_test.go, app/pkg/web/engine.go, app/pkg/web/testdata/basic.html, app/pkg/web/testdata/canonical.html, app/pkg/web/testdata/chunk.html, app/pkg/web/testdata/home.html, app/pkg/web/testdata/home_ssr.html, app/pkg/web/testdata/oauth.html, app/pkg/web/testdata/tenant.html, app/pkg/web/testdata/user.html, package-lock.json, package.json, public/assets/styles/variables.scss, views/base.html
This is an alternative solution for packaging up the Inter font with the app, rather than dubious GDPR issues linking it from google directly.
Fixes #1279
=> Sourcing the fonts from the inter NPM package

app/services/email/email_test.go, app/services/email/mailgun/sendmail_test.go, public/assets/styles/utility/text.scss, public/assets/styles/variables/_sizing.scss, public/assets/styles/variables/_spacing.scss, public/components/common/Dropdown.scss, public/components/common/Markdown.scss, public/pages/Home/components/ListPosts.tsx, public/pages/ShowPost/ShowPost.page.scss, public/pages/ShowPost/ShowPost.page.tsx, public/pages/ShowPost/components/ShowComment.scss, public/pages/ShowPost/components/ShowComment.tsx, views/email/base_email.html
**Issue:** https://github.com/getfider/fider/issues/1333
- I added a word-break class to allow easy breaking of long titles etc.
- I noticed that the spacing and sizing scss files where wrongly named and fixed that.
- Code blocks now have scrolling to prevent horizontal page scrolling.
- Comments have a calculated max width to prevent breaking the layout.
Also added:
- Better line breaking in mails
=> Improved handling of long strings in titles and code blocks (#1333)

app/actions/signin.go, app/handlers/signin.go, app/tasks/signin.go, app/tasks/signin_test.go, public/pages/Home/Home.page.tsx, public/pages/Home/components/ShareFeedback.tsx
Fixes a few issues with the new share feedback page:
- Form reappears if you cancel from a new signup
- Readonly sites were still allowing the form to enter a new post to be completed
=> Share feedback fixes

locale/fr/client.json, public/pages/Home/components/ShareFeedback.tsx
I saw this issue on the fider feedback page and noticed that uploading a picture as the first element will set the markdown for the image as a title.
I also fixed the translation typo that this issue was made for.
**Issue:** https://feedback.fider.io/posts/580/fider-image-attachments-yz2wdhy0c7cxfjrshihgyvszjjp33efu1xp4cbtmma8osfic603p
What I changed:
- "Filter" translation in FR
- images will no longer set the title of an idea
- manually clearing the title will reset the "manually edited" flag
=> France translation error and improved idea title behaviour

app/services/email/awsses/awsses.go, app/services/email/mailgun/sendmail.go, app/services/email/message.go, app/services/email/message_test.go, app/services/email/smtp/smtp.go
- Add EncodeSubject function to properly encode non-ASCII characters in email subject headers
- Use Go's built-in mime.QEncoding which implements RFC 2047 quoted-printable encoding
- Apply encoding in all email services: SMTP, Mailgun, and AWS SES
- ASCII-only subjects remain unencoded for compatibility
- Add comprehensive tests for the encoding function
This fixes issues with non-ASCII characters (umlauts, accents, emojis) in email subjects that were previously displayed incorrectly in some email clients and servers.
Resolves compatibility issues with downstream SMTP servers that don't support SMTPUTF8.
Fixes https://github.com/getfider/fider/issues/1147
=> fix: encode email subject headers according to RFC 2047
