getfider/fider

- wercker.yml
> update to node 8.1

- public/pages/site/SiteHomePage.scss
- public/pages/site/SiteHomePage.tsx
> show only initial 20 ideas and allow user to view more

- public/components/IdeaFilter.tsx
- public/pages/site/CompleteSignInProfilePage.tsx
- public/pages/site/SiteHomePage.scss
- public/pages/site/SiteHomePage.tsx
- public/utils/page.ts
> add search field

- public/pages/site/SiteHomePage.tsx
This fixes an issue created on #177
> prevent replaceState on load

- app/actions/tag.go
- app/handlers/tag.go
- app/handlers/tag_test.go
- app/middlewares/setup.go
- app/models/feedback.go
- app/pkg/jsonq/jsonq.go
- app/pkg/jsonq/jsonq_test.go
- app/pkg/mock/setup.go
- app/pkg/web/binder.go
- app/pkg/web/binder_test.go
- app/services.go
- app/storage/inmemory/tag.go
- app/storage/postgres/tag.go
- app/storage/postgres/tag_test.go
- app/storage/storage.go
- migrations/201711152138_create_tags.up.sql
- migrations/201711181740_create_uniq_indexes.up.sql
This PR includes most of the backend work for tag management #161
> API to manage/assign/unassign tags

- app/storage/inmemory/tenant.go
- app/storage/postgres/tenant.go
- app/storage/postgres/tenant_test.go
> fix for issue 197 + unit test

- public/assets/styles/main.scss
> bugfix: include word-wrap: break-word for markdown textx

- app/actions/idea.go
- app/models/feedback.go
- app/storage/postgres/idea.go
- app/storage/postgres/idea_test.go
- app/storage/postgres/tag.go
- public/models/idea.ts
- public/pages/admin/AdminHomePage.tsx
- public/pages/site/HomePage/HomePage.scss
- public/pages/site/HomePage/HomePage.tsx
- public/pages/site/HomePage/IdeaFilter.tsx
- public/pages/site/ShowIdeaPage/ResponseForm.tsx
- public/services/Session.ts
- tests/lib/mailgun/index.ts
This PR closes #210, #212, #194 and #207
> general fixes + planned status

- app/actions/actions_test.go
- app/actions/idea.go
- app/actions/idea_test.go
- app/handlers/idea_test.go
- app/storage/inmemory/idea.go
- app/storage/postgres/idea.go
- app/storage/postgres/idea_test.go
- app/storage/storage.go
- migrations/201712131842_unique_slug.up.sql
> Block submission of ideas with exact same title

- .gitignore
- .test.env
- .travis.yml
- Makefile
- docker-compose.yml
- package.json
- scripts/e2e.sh
- tests/context.ts
- tests/e2e-multi.ts
- tests/e2e-single.ts
- tests/lib/mailgun/index.ts
- tests/pages/HomePage.ts
- tests/pages/SignUpPage.ts
> run e2e on single tenant + more stability + scripts

- app/actions/idea.go
- app/handlers/idea_test.go
- app/models/feedback.go
- app/storage/postgres/idea.go
- app/storage/postgres/idea_test.go
> bugfix: nil err when status change from open to open

- app/middlewares/jwt.go
- app/middlewares/jwt_test.go
- app/models/feedback.go
- app/storage/postgres/idea.go
- app/storage/postgres/idea_test.go
- public/components/SupportCounter.tsx
- public/models/idea.ts
> replace second query with a subquery

- app/models/feedback.go
- app/storage/postgres/idea.go
- public/models/idea.ts
- public/pages/site/HomePage/IdeaFilter.tsx
> sort by trending ideas (like hackernews)

- public/assets/styles/main.scss
- views/base.html
> add a noscript tag

- Dockerfile
> Update docker default port to 3000

- app/actions/idea.go
- app/handlers/idea.go
- app/handlers/idea_test.go
- app/models/feedback.go
- app/pkg/jsonq/jsonq.go
- app/pkg/jsonq/jsonq_test.go
- app/storage/inmemory/idea.go
- app/storage/postgres/idea.go
- app/storage/postgres/idea_test.go
- app/storage/postgres/user.go
- app/storage/storage.go
- migrations/201801031643_duplicate_id.up.sql
- migrations/201801031643_original_id.up.sql
- package-lock.json
- package.json
- public/components/ShowIdeaResponse.tsx
- public/index.tsx
- public/models/idea.ts
- public/pages/site/HomePage/HomePage.tsx
- public/pages/site/HomePage/IdeaFilter.tsx
- public/pages/site/ShowIdeaPage/IdeaSearch.tsx
- public/pages/site/ShowIdeaPage/ResponseForm.tsx
- public/pages/site/ShowIdeaPage/ShowIdeaPage.scss
- public/pages/site/ShowIdeaPage/index.ts
- public/router.tsx
- public/services/actions/idea.ts
- public/services/http.ts
- routes.go
- scripts/e2e.sh
> [WIP] Duplicate Status

- app/actions/idea.go
- app/actions/idea_test.go
- app/actions/signin.go
- app/actions/signin_test.go
- app/handlers/signin.go
- app/handlers/signin_test.go
- app/handlers/signup.go
- app/models/identity.go
- app/storage/inmemory/tenant.go
- app/storage/postgres/tenant.go
- app/storage/postgres/tenant_test.go
- app/storage/storage.go
- migrations/201801152006_rename_signin_requests.up.sql
- migrations/201801152017_add_kind_email_verification.up.sql
- public/pages/site/ShowIdeaPage/ShowIdeaPage.tsx
- routes.go
This is necessary setup for #225
> Rename signin_requests and add kind as column

- public/assets/styles/main.scss
- public/components/ShowTag.tsx
- public/pages/site/ShowIdeaPage/ShowIdeaPage.scss
- public/pages/site/ShowIdeaPage/ShowIdeaPage.tsx
> bugfix: fix for layout issue and textcolor

- app/models/feedback.go
- app/storage/inmemory/idea.go
- app/storage/inmemory/user.go
- app/storage/postgres/idea.go
- app/storage/postgres/subscription_test.go
- app/storage/postgres/user.go
- app/storage/storage.go
- migrations/201802061858_create_notification_tables.up.sql
- migrations/201802071816_seed_subscribers_table.up.sql
> Add subscribers and automatically subscribe on new idea, vote and new comment

- app/handlers/signup.go
- app/models/feedback.go
- app/pkg/email/email.go
- app/pkg/email/email_test.go
- app/pkg/email/mailgun/mailgun.go
- app/pkg/email/smtp/smtp.go
- app/storage/inmemory/idea.go
- app/storage/postgres/subscription_test.go
- app/tasks/tasks.go
- app/tasks/tasks_test.go
- tests/lib/mailgun/index.ts
- views/templates/change_emailaddress_email.tpl
- views/templates/signin_email.tpl
- views/templates/signup_email.tpl
> Add BatchSend to both SMTP and Mailgun packages

- public/pages/site/HomePage/HomePage.tsx
- routes.go
> fix: make api public and tweak when lonely is shown

- app/handlers/notification.go
- app/handlers/notification_test.go
- app/middlewares/setup.go
- app/models/infra.go
- app/pkg/jsonq/jsonq.go
- app/pkg/jsonq/jsonq_test.go
- app/pkg/mock/setup.go
- app/services.go
- app/storage/inmemory/notifications.go
- app/storage/postgres/notifications.go
- app/storage/postgres/notifications_test.go
- app/storage/postgres/setup_test.go
- app/storage/storage.go
- app/tasks/tasks.go
- migrations/201802241348_create_webnotification_tables.up.sql
- public/assets/styles/main.scss
- public/components/common/Header.tsx
- public/models/index.ts
- public/models/notification.ts
- public/pages/site/UserNotificationsPage/UserNotificationsPage.scss
- public/pages/site/UserNotificationsPage/UserNotificationsPage.tsx
- public/pages/site/UserNotificationsPage/index.ts
- public/pages/site/UserSettingsPage/NotificationSettings.tsx
- public/router.tsx
- public/services/actions/index.ts
- public/services/actions/notification.ts
- public/services/page.ts
- routes.go
> feature: implement web notifications

- app/handlers/avatar.go
Although not sure yet, this could help fix this leak #286
> fix: close response body from avatar get

- app/pkg/web/engine.go
Based on https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
Might help solve #286
> fix: add server timeouts

- app/handlers/avatar.go
- app/pkg/email/mailgun/mailgun.go
this might finally complete #286
> fix: close http request on mailgun

- app/actions/actions_test.go
- app/actions/user.go
- app/actions/user_test.go
- app/handlers/settings.go
- app/handlers/settings_test.go
- app/handlers/signin.go
- app/handlers/signin_test.go
- app/handlers/signup.go
- app/handlers/signup_test.go
- app/pkg/dbx/setup.sql
- app/storage/inmemory/user.go
- app/storage/postgres/idea.go
- app/storage/postgres/idea_test.go
- app/storage/postgres/setup_test.go
- app/storage/postgres/subscription_test.go
- app/storage/postgres/tag.go
- app/storage/postgres/user.go
- app/storage/postgres/user_test.go
- app/storage/storage.go
- migrations/201803011831_add_tenant_id_everywhere.up.sql
This fixes: https://github.com/getfider/fider/issues/279 and https://github.com/getfider/fider/issues/281
> refactor: add new column and FKs

- public/services/utils.ts
- public/tsd.d.ts
- scripts/e2e.sh
- tests/tsconfig.json
- tsconfig.json
Fix rendering on ie11 due to non-available function.
> fix: issue with ie11 rendering

- .circleci/config.yml
- docker-compose.yml
- scripts/e2e.sh
Update postgres dependency to 9.6.8
> chore: update to 9.6.8

- public/assets/styles/main.scss
- public/assets/styles/variables.scss
- public/components/SignInModal.tsx
- public/components/SupportCounter.tsx
- public/components/common/Header.tsx
- public/components/common/Modal.scss
- public/components/common/Modal.tsx
- public/components/common/SignInControl.tsx
- public/components/common/index.tsx
- public/index.tsx
- public/pages/CompleteSignInProfile/CompleteSignInProfile.page.tsx
- public/pages/Home/components/IdeaInput.tsx
- public/pages/MySettings/MySettings.page.tsx
- public/pages/ShowIdea/components/CommentInput.tsx
- public/pages/ShowIdea/components/ResponseForm.tsx
- public/pages/SignUp/SignUp.page.tsx
- public/services/device.ts
- public/services/index.ts
- public/services/page.ts
- tests/pages/HomePage.ts
- tests/pages/ShowIdeaPage.ts
- tests/pages/SignUpPage.ts
- views/index.html
**Issue:** part of #171
Replacing SemanticUI Modal with custom modal.
> enhancement: custom modal

- app/middlewares/setup.go
- app/middlewares/setup_test.go
- app/pkg/mock/server.go
- app/pkg/mock/worker.go
- app/pkg/web/context.go
**Issue:** closes #313
This fix only sends task to worker queue after transaction is committed.
> fix: #313 by enqueuing it only after commit

- app/actions/idea.go
- app/actions/idea_test.go
- app/handlers/idea.go
- app/handlers/idea_test.go
- app/models/feedback.go
- app/pkg/web/binder.go
- app/pkg/web/binder_test.go
- app/pkg/web/context.go
- app/pkg/web/context_test.go
- app/storage/inmemory/idea.go
- app/storage/postgres/idea.go
- app/storage/postgres/idea_test.go
- app/storage/storage.go
- public/pages/ShowIdea/ShowIdea.page.tsx
- public/pages/ShowIdea/components/ModerationPanel.tsx
- public/pages/ShowIdea/index.ts
- public/services/actions/idea.ts
- public/services/page.ts
- routes.go
- tests/pages/GoogleSignInPage.ts
**Issue:** closes #311
This PR includes a button (only visible to administrators) that allows them to delete existing ideas.
> feature: add button to delete ideas

- app/storage/postgres/idea.go
- package-lock.json
- package.json
- public/assets/styles/main.scss
- public/assets/styles/variables.scss
- public/components/common/Modal.scss
- public/components/common/index.tsx
- public/index.tsx
- public/pages/Home/Home.page.scss
- public/pages/Home/components/IdeaFilter.tsx
- public/pages/Home/components/IdeasContainer.tsx
- public/pages/Home/components/ListIdeas.tsx
- public/pages/Home/components/TagsFilter.tsx
- public/pages/ShowIdea/ShowIdea.page.scss
- public/pages/ShowIdea/components/IdeaSearch.tsx
- public/pages/ShowIdea/components/TagsPanel.tsx
- public/tsd.d.ts
- tsconfig.json
**Issue:** closes #171
- Introduced semantic-ui-react to remove jQuery.
- Minor UI changes/refactoring.
> Add semantic react

- public/components/common/Modal.tsx
> fix: bug 323

- README.md
- app/middlewares/domain.go
- public/components/common/Footer.tsx
- public/pages/Home/components/IdeaFilter.tsx
- tsconfig.json
- views/403.html
- views/404.html
- views/500.html
- views/base.html
- Use HTTPS for getfider.com
- Use ES5
> chore: use HTTPS and ES5

- app/middlewares/security.go
- app/middlewares/security_test.go
- routes.go
**Issue:**  part of #293
Introduces following security headers:
- X-XSS-Protection
- X-Content-Type-Options
- Referrer-Policy
> add few basic http security headers

- public/components/common/Toggle.scss
- public/components/common/Toggle.tsx
- public/components/common/index.tsx
- public/pages/MySettings/MySettings.page.scss
- public/pages/MySettings/components/NotificationSettings.tsx
**Issue:**  parts of #326
Replaces image toggle with a real toggle component.
Cross-browser compatible with pure-css styling.
> introducing a toggle component

- app/handlers/signin_test.go
- app/middlewares/domain.go
- app/middlewares/domain_test.go
- app/pkg/mock/setup.go
- app/pkg/web/context.go
- app/pkg/web/context_test.go
**Issue:**  closes #274
Adds a Canonical Link HTTP Header whenever custom domain is set.
> enhancement: add canonical link whenever using custom domains

- app/handlers/common.go
- app/handlers/common_test.go
- app/middlewares/security.go
- app/middlewares/security_test.go
- app/pkg/web/context.go
- app/pkg/web/context_test.go
- app/pkg/web/engine.go
- app/pkg/web/renderer.go
- routes.go
- views/base.html
**Issue:**  part of #293
Add two new security headers:
- Content Security Policy (Report Only for now)
- Deny X-Frame-Options
> enhancement: add csp-report policy

- app/middlewares/security.go
- app/middlewares/security_test.go
> fix: allow use of Fider on frames

- app/middlewares/security.go
- app/middlewares/security_test.go
- app/pkg/web/engine.go
**Issue:** closes #293
Enables Content Security Policy.
> enhancement: enable CSP

- .circleci/config.yml
- CONTRIBUTING.md
- Makefile
- package-lock.json
- package.json
- public/services/utils.spec.tsx
**Issue:**  part of #361 
- Updates to Node 10
- Pin all NPM packages
> tooling: update to Node 10 and pin packages

- .circleci/config.yml
> tooling: update to latest go version

- app/cmd/routes.go
- app/cmd/server.go
- app/handlers/admin.go
- app/pkg/env/env.go
- app/pkg/env/env_test.go
- public/pages/Administration/pages/GeneralSettings.page.tsx
> fix: show correct DNS instructions when using apex domain

- Makefile
- app/pkg/dbx/dbx_test.go
- app/pkg/dbx/mapping.go
- migrations/201805061319_create_uploads.up.sql
- public/assets/styles/main.scss
- public/assets/styles/variables.scss
- public/components/common/Header.tsx
- views/base.html
**Issue:**  part of #367
- Remove Ubuntu font;
- Larger header;
- Support for bytea on DBX;
> chore: part 1 of "Customize Look and Feel"

- app/cmd/routes.go
- app/handlers/admin.go
- app/handlers/common.go
- app/handlers/idea.go
- app/handlers/notification.go
- app/handlers/settings.go
- app/handlers/signin.go
- app/handlers/signup.go
- app/handlers/tag.go
- app/pkg/markdown/markdown.go
- app/pkg/markdown/markdown_test.go
- app/pkg/markdown/renderer.go
- app/pkg/web/context.go
- app/pkg/web/renderer.go
- public/pages/Administration/pages/Export.page.tsx
- public/pages/Administration/pages/GeneralSettings.page.tsx
- public/pages/Administration/pages/Invitations.page.tsx
- public/pages/Administration/pages/ManageMembers.page.tsx
- public/pages/Administration/pages/ManageTags.page.tsx
- public/pages/Administration/pages/PrivacySettings.page.tsx
- public/pages/ShowIdea/ShowIdea.page.tsx
- public/pages/SignIn/SignIn.page.tsx
- public/pages/SignUp/SignUp.page.tsx
- public/services/page.ts
- views/403.html
- views/404.html
- views/410.html
- views/500.html
- views/base.html
- views/index.html
**Issue:**  part of #367 closes #168
> feature: Better SEO title+description

- app/pkg/web/context.go
- app/pkg/web/context_test.go
- app/pkg/web/renderer.go
- views/base.html
> fix: include full url to og:url

- app/storage/postgres/tag.go
- app/storage/postgres/tag_test.go
- public/assets/styles/main.scss
- public/assets/styles/variables.scss
- public/components/ShowTag.scss
- public/components/common/Header.scss
- public/components/common/Heading.scss
- public/components/common/Heading.tsx
- public/pages/Administration/pages/ManageTags.page.tsx
- public/pages/Home/Home.page.scss
- public/pages/Home/components/IdeasContainer.tsx
- public/pages/UI/UIToolkit.page.tsx
**Issue:**  closes #366
- Order tags by name
- Group tags by visibility
> enhancement: group tags by visibility + order by name

- app/actions/idea.go
- app/pkg/web/renderer.go
- public/assets/styles/main.scss
- public/assets/styles/variables.scss
- public/components/common/Button.scss
- public/components/common/Footer.scss
- public/components/common/Header.scss
- public/components/common/Header.tsx
- public/components/common/SignInControl.scss
- public/components/common/form/Form.scss
- public/pages/Home/Home.page.tsx
- public/pages/Home/components/IdeaInput.tsx
- public/pages/ShowIdea/ShowIdea.page.scss
- public/pages/ShowIdea/ShowIdea.page.tsx
- views/base.html
- better spacing
- center align on SignIn page
- better default text
> enhancement: minor UI changes

- main.go
- public/assets/styles/main.scss
- public/components/ShowIdeaResponse.tsx
- public/components/common/Footer.scss
- public/components/common/Gravatar.scss
- public/components/common/Gravatar.tsx
- public/components/common/Header.scss
- public/pages/Home/Home.page.scss
- public/pages/Home/Home.page.tsx
- public/pages/Home/components/IdeasContainer.tsx
- Larger right column on home page
- Better filter positioning
- Smaller Avatars
> enhancement: minor design changes

- app/cmd/routes.go
- app/middlewares/cors.go
- app/middlewares/cors_test.go
- app/pkg/web/renderer.go
- views/base.html
- webpack.config.js
> refactoring: compile vendor packages into a separate bundle

- app/handlers/idea.go
- app/storage/inmemory/idea.go
- app/storage/postgres/common.go
- app/storage/postgres/idea.go
- app/storage/postgres/idea_test.go
- app/storage/storage.go
- public/pages/Home/Home.page.tsx
- public/pages/Home/components/IdeaFilter.tsx
- public/pages/Home/components/IdeaInput.tsx
- public/pages/Home/components/IdeasContainer.tsx
- public/pages/Home/components/ListIdeas.scss
- public/pages/Home/components/ListIdeas.tsx
- public/pages/Home/components/SimilarIdeas.tsx
- public/pages/ShowIdea/components/IdeaSearch.tsx
- public/services/actions/idea.ts
- public/services/page.ts
**Issue:** part of #403. closes #406
> enhancement: home page improvements

- app/actions/actions_test.go
- app/handlers/signin.go
- app/handlers/signin_test.go
- app/handlers/signup_test.go
- app/middlewares/jwt_test.go
- app/models/identity.go
- app/pkg/jwt/jwt.go
- app/pkg/jwt/jwt_test.go
- app/pkg/web/context.go
- app/pkg/web/engine.go
> enhancement: add expiry date to jwt tokens

- app/actions/idea.go
- app/handlers/idea.go
- app/tasks/tasks.go
- public/components/ShowIdeaResponse.tsx
- public/components/common/Segment.scss
- views/templates/change_status.tpl
> enhancement: make comment optional when responding to an idea 

- app/pkg/web/engine.go
- app/pkg/web/ssl.go
> enhancement: Remove support for TLS 1.0, TLS 1.1 and old ciphers

- Makefile
- app/pkg/assert/assert_test.go
- app/pkg/dbx/mapping.go
- app/pkg/dbx/mapping_test.go
- app/pkg/worker/worker.go
- app/pkg/worker/worker_test.go
> bugfix: turn on race condition flag and add mutex everywhere

- app/middlewares/setup.go
- app/pkg/assert/assert.go
- app/pkg/email/mailgun/mailgun.go
- app/pkg/email/mailgun/mailgun_test.go
- app/pkg/email/smtp/smtp.go
- app/pkg/email/smtp/smtp_test.go
- app/pkg/mock/client.go
- app/pkg/web/client.go
- app/services.go
> refactoring: unit tests for mailgun+smtp

- app/middlewares/setup.go
- app/pkg/email/email.go
- app/pkg/email/noop/noop.go
- app/pkg/markdown/markdown.go
- app/pkg/markdown/markdown_test.go
- app/pkg/mock/setup.go
- app/pkg/mock/worker.go
- app/storage/inmemory/idea.go
- app/tasks/tasks.go
- app/tasks/tasks_test.go
> refactoring: unit tests for background tasks

- main.go
> chore: update Fider version

- app/handlers/signin.go
- main.go
- public/assets/styles/main.scss
- public/components/common/Heading.scss
- public/pages/Administration/components/AdminBasePage.tsx
- public/pages/Administration/components/SideMenu.scss
- public/pages/Administration/components/SideMenu.tsx
> enhancement: collapsable side menu on small screens

- app/pkg/mock/oauth.go
- app/pkg/oauth/oauth.go
- app/pkg/web/oauth.go
- app/pkg/web/renderer.go
- public/components/common/SignInControl.tsx
- public/components/common/SocialSignInButton.tsx
- public/models/settings.ts
- public/pages/UI/UIToolkit.page.tsx
> refactor: get list of OAuth providers from server

- app/pkg/jsonq/jsonq.go
- app/pkg/jsonq/jsonq_test.go
> enhancement: add support for array selector on jsonq

- Gopkg.lock
- vendor/github.com/lib/pq/README.md
- vendor/github.com/lib/pq/TESTS.md
- vendor/github.com/lib/pq/connector.go
- vendor/github.com/lib/pq/connector_example_test.go
- vendor/github.com/lib/pq/connector_test.go
- vendor/golang.org/x/oauth2/cern/cern.go
- vendor/golang.org/x/oauth2/gitlab/gitlab.go
- vendor/golang.org/x/oauth2/internal/token.go
- vendor/golang.org/x/oauth2/jira/jira.go
- vendor/golang.org/x/oauth2/kakao/kakao.go
- vendor/golang.org/x/oauth2/linkedin/linkedin.go
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/oauth2_test.go
- vendor/golang.org/x/oauth2/stackoverflow/stackoverflow.go
- vendor/golang.org/x/oauth2/transport.go
- vendor/golang.org/x/oauth2/transport_test.go
- vendor/golang.org/x/oauth2/twitch/twitch.go
> enhancement: update Go packages

- public/pages/CompleteSignInProfile/CompleteSignInProfile.page.tsx
> bugfix: handle 'Enter' key when completing the profile

- app/pkg/jsonq/jsonq.go
- app/pkg/jsonq/jsonq_test.go
- app/pkg/web/oauth.go
- app/pkg/web/oauth_test.go
> refactor: use new Google OAuth API

- app/pkg/web/context.go
- app/pkg/web/oauth.go
- app/pkg/web/request.go
- app/pkg/web/request_test.go
- app/pkg/web/util/webutil.go
> enhancement: force secure cookies when running on HTTPS

- app/cmd/routes.go
- app/middlewares/domain.go
- app/middlewares/domain_test.go
- app/pkg/mock/server.go
> refactor: organize tenant middleware into Get + Require

- app/middlewares/setup.go
- app/pkg/web/context.go
> enhancement: add UserAgent to error logs

- app/pkg/log/database/logger.go
> bugfix: make database logs run sync

- app/handlers/oauth.go
> bugfix: increase cookie time to 2 hours

- app/handlers/oauth.go
- app/pkg/web/request.go
> enhancement: redirect instead of error

- public/components/common/Button.tsx
- public/components/common/SocialSignInButton.tsx
> enhancement: Google should not follow sign in links

- app/pkg/web/context.go
> fix: force redirect to not be cached

- app/actions/actions_test.go
- app/actions/idea.go
- app/actions/invite.go
- app/actions/oauth.go
- app/actions/oauth_test.go
- app/actions/signin.go
- app/actions/tag_test.go
- app/actions/tenant.go
- app/actions/user.go
- app/handlers/signup.go
- app/handlers/tag_test.go
- app/pkg/validate/general.go
- app/pkg/validate/general_test.go
- app/pkg/validate/subdomain.go
- app/pkg/validate/subdomain_test.go
- app/pkg/validate/upload.go
- app/pkg/validate/upload_test.go
- app/pkg/validate/validation.go
- app/pkg/validate/validation_test.go
- app/pkg/web/context.go
- app/pkg/web/oauth.go
- public/components/common/form/DisplayError.spec.tsx
- public/components/common/form/DisplayError.tsx
- public/pages/Administration/pages/ManageAuthentication.page.tsx
- public/pages/UI/UIToolkit.page.tsx
- public/services/http.ts
> enhancement: standardised error response

- app/handlers/images.go
- app/pkg/web/client.go
> fix: resolve test flakiness 

- app/actions/user.go
- app/actions/user_test.go
> enhancement: better change role validation

- app/cmd/routes.go
- app/handlers/apiv1/post.go
- app/handlers/apiv1/post_test.go
- app/handlers/apiv1/tag.go
- app/handlers/apiv1/tag_test.go
- app/handlers/apiv1/user.go
- app/handlers/apiv1/user_test.go
> enhancement: a few missing API operations

- app/cmd/routes.go
- app/pkg/web/engine.go
- app/pkg/web/engine_test.go
> refactor: reorganize web router

- app/handlers/settings_test.go
- app/models/feedback.go
- app/storage/postgres/notifications.go
- app/storage/postgres/post.go
- app/storage/postgres/post_test.go
- app/storage/postgres/tag.go
- app/storage/postgres/user.go
- migrations/201808152020_rename_idea_post.sql
- public/pages/MySettings/components/NotificationSettings.tsx
> refactoring: rename all database objects from idea to post

- app/cmd/routes.go
- app/middlewares/auth.go
- app/middlewares/auth_test.go
- app/middlewares/domain.go
- app/pkg/jwt/jwt.go
- app/pkg/mock/server.go
- app/pkg/web/context.go
- app/pkg/web/request.go
- app/pkg/web/request_test.go
- app/pkg/web/util/webutil.go
> enhancement: block non-api resources for API-originated tokens

- app/actions/oauth.go
- app/actions/oauth_test.go
- app/handlers/oauth.go
- app/pkg/dbx/dbx_test.go
- app/pkg/mock/oauth.go
- app/pkg/oauth/oauth.go
- app/pkg/web/oauth.go
- public/pages/Administration/components/OAuthForm.tsx
- public/pages/OAuthEcho/OAuthEcho.page.tsx
**Issue:** might help troubleshoot #489
> feature: parse OAuth profile from Access Token

- app/middlewares/domain.go
- app/middlewares/domain_test.go
- app/pkg/web/context.go
- app/storage/postgres/user.go
> enhancement: reject requests with invalid API Key

- app/middlewares/domain.go
- app/middlewares/domain_test.go
> enhancement: reject API key from visitors

- package-lock.json
- package.json
ref: fkhadra/react-toastify#215
> fix: rollback react-toastify to 4.1.0 due to ie11 issue

- app/models/identity.go
- app/storage/postgres/user.go
- app/storage/postgres/user_test.go
- public/components/SupportCounter.spec.tsx
- public/models/identity.ts
- public/pages/UI/UIToolkit.page.tsx
> enhancement: don't return deleted user

- app/cmd/routes.go
- app/middlewares/domain.go
> fix: move routes after loading tenant info

- app/actions/user.go
- app/actions/user_test.go
- app/cmd/routes.go
- app/handlers/apiv1/user.go
- app/handlers/apiv1/user_test.go
- app/models/identity.go
> feature: new API to create users

- app/cmd/routes.go
- app/pkg/web/engine.go
> fix: show site branding on 404 page

- app/pkg/web/context.go
- app/pkg/web/engine.go
> enhancement: log UserAgent on every request

- app/handlers/oauth.go
**Issue:** potential fix for #519
> fix: increase expire date to 24 hours

- app/middlewares/setup.go
> fix: catch panic earlier

- CONTRIBUTING.md
- magefile.go
> refactor: use mage aliases

- app/handlers/apiv1/post.go
- app/handlers/post.go
- app/storage/inmemory/post.go
- app/storage/postgres/common.go
- app/storage/postgres/post.go
- app/storage/storage.go
- public/pages/Home/components/PostFilter.tsx
- public/pages/Home/components/PostsContainer.tsx
- public/services/actions/post.ts
**Issue:**  part of #440 
- `f` -> `view`
- `q` -> `query`
- `t` -> `tags`
- `l` -> `limit`
> refactor: rename QueryString filters

- app/handlers/apiv1/post.go
- app/models/feedback.go
- public/pages/Administration/components/TagListItem.tsx
- public/pages/Administration/pages/ManageTags.page.tsx
- public/pages/ShowPost/components/ShowComment.tsx
- public/services/actions/post.ts
> refactoring: typos, better API response

- public/components/common/SignInControl.tsx
> chore: add more CSS classes for SignIn Control

- public/pages/MySettings/MySettings.page.tsx
- public/pages/MySettings/components/APIKeyForm.tsx
**Issue:**  closes #440
Finally! 😁
> feature: enable API Key

- app/pkg/web/request.go
**Issue:**  The ClientIP logic didn't use the existing net.SplitHostPort function. 
This PR refactors the ClientIP extraction logic to better express the intent/flow of how the ClientIP is determined and uses the built in net.SplitHostPort. SplitHostPort supports a wider range of potential IP Address formats.
> Refactor ClientIP extraction logic

- app/cmd/routes.go
- app/handlers/common.go
- app/handlers/common_test.go
- app/pkg/web/context.go
- Add a dynamic (and very basic) sitemap to every root site.;
- Private sites will not generate a sitemap.xml;
- Sitemap does not yet include other pages aside from homepage and all posts;
> feature: add sitemap.xml

- public/assets/styles/main.scss
- public/assets/styles/variables.scss
- public/components/common/DropDown.scss
- public/components/common/DropDown.tsx
- public/components/common/UserName.scss
- public/pages/ShowPost/components/Comments.scss
- public/pages/ShowPost/components/ShowComment.tsx
This is required to implement future features like delete or flag a comment.
> refactor: move comment actions to a dropdown

- app/pkg/web/renderer.go
- public/components/common/Gravatar.tsx
- public/models/settings.ts
- public/services/fider.ts
- public/services/utils.ts
- public/tsd.d.ts
- views/base.html
- views/index.html
Issue: #588 
Required for CDN reference on webpack when code-splitting.
> enhancement: expose extra system params

- app/handlers/images.go
> return 404 for invalid id/size

- app/handlers/oauth.go
- app/handlers/oauth_test.go
- app/pkg/mock/server.go
- scripts/e2e.sh
> enhancement: use session id for OAuth validation

- app/pkg/web/renderer.go
- public/index.tsx
- views/base.html
- views/index.html
- webpack.config.js
> feature: add a common chunk

- public/AsyncPages.tsx
> enhancement: retry async chunks when it fails

- app/handlers/apiv1/post.go
- app/handlers/apiv1/user.go
- app/models/identity.go
> enhancement: add user email on users API

- app/cmd/migrate.go
- app/pkg/dbx/dbx.go
- app/pkg/log/console/logger.go
- app/pkg/log/database/logger.go
- app/pkg/log/log.go
- app/pkg/log/noop/logger.go
- docker-compose.yml
**Issue:** #653
Enables full log for the migration process
> fix: use console logger for migration

- app/pkg/dbx/dbx.go
- app/pkg/dbx/dbx_test.go
- public/components/common/Logo.tsx
- public/pages/Error/Error.page.tsx
> fix: dbx was setting to null when there were no values in array

- app/storage/postgres/post.go
- public/pages/ShowPost/components/VotesPanel.tsx
> fix: dont break when voters is 0

- app/handlers/post.go
- app/middlewares/tenant.go
- app/middlewares/tenant_test.go
- app/pkg/web/context.go
- app/pkg/web/context_test.go
- app/pkg/web/renderer.go
- app/pkg/web/renderer_test.go
- app/pkg/web/testdata/basic.html
- app/pkg/web/testdata/canonical.html
- app/pkg/web/testdata/chunk.html
- app/pkg/web/testdata/props.html
- app/pkg/web/testdata/user.html
- views/base.html
> enhancement: set canonical link on HTML

- .test.env
- app/actions/actions_test.go
- app/middlewares/setup.go
- app/pkg/blob/blob.go
- app/pkg/blob/blob_test.go
- app/pkg/blob/fs/fs.go
- app/pkg/blob/s3/s3.go
- app/pkg/blob/sql/sql.go
- app/pkg/di/blob.go
- app/pkg/mock/setup.go
- app/services.go
> refactoring: cleaner usage of blob storage

- webpack.config.js
> Small comment typo

- public/components/common/Button.scss
- public/components/common/form/ImageUploader.scss
- public/components/common/form/ImageUploader.tsx
- public/models/settings.ts
- public/pages/Administration/components/OAuthForm.tsx
- public/pages/Administration/pages/GeneralSettings.page.tsx
- public/services/actions/tenant.ts
- public/services/utils.ts
> refactor: image upload

- app/handlers/common.go
- app/handlers/images.go
> fix: force min/max size values

- app/pkg/log/database/logger.go
- app/pkg/log/database/logger_test.go
> fix: write logs on a separate goroutine

- app/pkg/markdown/markdown.go
- app/pkg/markdown/markdown_test.go
- public/services/markdown.spec.ts
- public/services/markdown.ts
> fix: sanitize input before parsing markdown

- app/pkg/web/context.go
> fix: use rendergun on React pages only and block ads

- app/actions/post.go
- app/handlers/apiv1/post.go
- app/models/feedback.go
- app/storage/postgres/post.go
- public/models/post.ts
- public/pages/ShowPost/components/CommentInput.tsx
- public/pages/ShowPost/components/ShowComment.tsx
- public/services/actions/post.ts
> feature: add attachments to comments

- public/components/common/EnvironmentInfo.tsx
- public/components/common/Logo.tsx
- public/components/common/TenantStatusInfo.tsx
- public/hooks/index.ts
- public/hooks/use-fider.ts
- public/index.tsx
- public/pages/Administration/components/BillingPlanPanel.tsx
- public/services/fider.ts
**Issue:** first step to of #736
> refactor: introduce FiderContext

- public/components/common/Toggle.tsx
- public/pages/Administration/components/OAuthForm.tsx
- public/pages/UI/UIToolkit.page.tsx
> refactor: migrate OAuthForm and UIToolkit to React Hooks

- app/handlers/apiv1/user.go
- app/handlers/apiv1/user_test.go
- migrations/20190409192142_fix_api_users_role.sql
> fix: set role to visitor for users created by api

- .circleci/config.yml
- CONTRIBUTING.md
- app/pkg/errors/errors_test.go
> tooling: update to Go 1.13.3

- public/components/common/form/Checkbox.tsx
**Issue:**  
[Migrate components under public/components to React Hooks [1st step] (**Checkbox** component) ](https://github.com/getfider/fider/issues/730)
In this PR, I migrate **Checkbox** class component to a **functional component** using **useState** hook.
**I changed the component from being uncontrolled to controlled using checked prop instead of defaultChecked**.
Thanks for your review
> Migrate Checkbox component to React functional component using useState hook

- public/components/common/Button.tsx
- public/components/common/SignInControl.tsx
- public/components/common/form/Input.tsx
- public/pages/CompleteSignInProfile/CompleteSignInProfile.page.tsx
- public/pages/Home/components/PostInput.tsx
> fix: enable submission of post when pressing enter

- app/cmd/server.go
- app/models/cmd/notification.go
- app/services/sqlstore/postgres/notification.go
- app/services/sqlstore/postgres/notifications_test.go
- app/services/sqlstore/postgres/postgres.go
- app/services/sqlstore/postgres/setup_test.go
> enhancement: purge notifications older than 1 year

- .dockerignore
- .github/workflows/fider.yml
- Dockerfile
- magefile.go
**Issue:** closes #767
This change means that we can now build the docker image without any prior step, everything is defined inside the Dockerfile
> tooling: use a multi-stage docker build

- app/pkg/web/ssl.go
> enhancement: add support for latest TLS version

- app/cmd/routes.go
- app/handlers/post.go
- app/handlers/post_test.go
> fix: redirect user to new url if slug has changed

- public/components/ErrorBoundary.tsx
- public/components/common/FiderVersion.tsx
- public/components/common/Footer.tsx
- public/components/common/Legal.tsx
- public/pages/Administration/components/SideMenu.tsx
- public/pages/Error/Error.page.spec.tsx
- public/pages/Error/Error.page.tsx
- public/pages/Home/Home.page.tsx
> refactor: remove Fider service from some components

- public/components/VoteCounter.tsx
- public/components/common/CardInfo.tsx
- public/components/common/Header.tsx
- public/components/common/SignInControl.tsx
- public/components/common/form/TextArea.tsx
- public/pages/Home/components/PostFilter.tsx
- public/pages/ShowPost/components/CommentInput.tsx
- public/pages/ShowPost/components/ModerationPanel.tsx
- public/pages/ShowPost/components/ShowComment.tsx
- public/pages/ShowPost/components/VotesPanel.tsx
> refactor: remove Fider service from some components (part 2)

- public/components/common/form/Input.tsx
- public/pages/Administration/components/TagListItem.tsx
- public/pages/Home/components/PostInput.tsx
- public/pages/MySettings/components/NotificationSettings.tsx
- public/pages/ShowPost/components/NotificationsPanel.tsx
- public/pages/ShowPost/components/TagsPanel.tsx
> refactor: remove global Fider service from non-page components

- public/components/common/Moment.tsx
- public/pages/Administration/components/BillingPlanPanel.tsx
- public/pages/ShowPost/components/VotesModal.scss
- public/pages/ShowPost/components/VotesModal.tsx
- public/services/utils.spec.ts
- public/services/utils.ts
> fix: better alignment of votes modal content on mobile devices

- public/components/common/Avatar.tsx
**Issue:**  https://github.com/getfider/fider/issues/837
User name added to props and title attribute updated to display basic name tooltip on avatar pic.
> Patch on Avatar.tsx to activate name tooltip via title attribute

- app/services/oauth/custom.go
- app/services/oauth/oauth.go
- app/services/oauth/oauth_test.go
https://dev.twitch.tv/docs/authentication/getting-tokens-oidc#claims
> fix: support twitch new oauth

- .example.env
**Issue:** Fixes [#936](https://github.com/getfider/fider/issues/936)
> Update Example Config for Version 0.18.1

- package.json
> fix: pin node 14.x

- app/actions/actions.go
- app/actions/post.go
- app/cmd/routes.go
- app/handlers/apiv1/post_test.go
- app/middlewares/setup.go
- app/pkg/mock/setup.go
- app/pkg/web/context.go
- public/pages/ShowPost/ShowPost.page.tsx
- public/services/utils.ts
**Idea:** https://feedback.fider.io/posts/164/allow-users-to-edit-the-ideas-they-submitted-for-clarity
- Users have 1 hour to edit their own post for clarity
> feature: allow users to edit their posts within 1 hour

- app/cmd/ping.go
- app/pkg/env/env.go
- app/pkg/web/autocert_test.go
- app/pkg/web/engine.go
- app/pkg/web/ssl.go
- app/pkg/web/ssl_test.go
- add ALPN as a supported acme challenge
- rename variables from SSL to TLS
- add logging
> feature: add ALPN as a supported acme challenge

- public/pages/ShowPost/components/VotesModal.tsx
**Issue:** https://github.com/getfider/fider/issues/730
Refactor the VotesModal component into hooks
> refactor: VotesModal into hooks

- public/pages/SignIn/SignIn.page.tsx
**Issue:** https://github.com/getfider/fider/issues/730 
Refactor the SignIn component to use hooks instead of class components
> refactor: SignIn to hooks

- .github/workflows/build.yml
- .github/workflows/publish.yml
- Dockerfile
- Makefile
- app/pkg/web/react.go
- go.mod
- go.sum
Release docker image for amd64 and arm64/v8
> chore: build on ARM

- README.md
**Issue:** Broken link in README.md fixes #1079
> fix: broken markdown in README.md

- public/pages/Administration/pages/GeneralSettings.page.tsx
Correct `understad` to `understand`
Resolves: #1110
> Fix typo in `Welcome Message` section

- go.mod
- go.sum
- package-lock.json
- package.json
Fixes dependabots #1191 #1187 #1184
> Dependabot batch 20240912

- app/cmd/routes.go
> Fixed gravatar for usernames with unusual characters

- README.md
Update the home page to have link to issue https://github.com/getfider/fider/issues/899
> Let us know if you're using fider :)

- public/pages/ShowPost/components/TagsPanel.tsx
> Don't show the edit link if no permissions.

- .github/workflows/build.yml
- app/services/userlist/userlist.go
- app/services/userlist/userlist_test.go
Cloud-hosting bug with the userlist code, if a user updated their email and wasn't an admin, it was creating the user in userlist.
> Userlist fixuserupdate

- public/assets/images/heroicons-lightbulb.svg
- public/components/ShowPostResponse.tsx
> Show "Open" post response if there is one
